ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
#FROM docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
#FROM docker.elastic.co/kibana/kibana:8.7.0
FROM peterlin495/kibana:kibana
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
