ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
#FROM docker.elastic.co/logstash/logstash:8.7.0
FROM peterlin495/logstash:logstash
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
